platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

def stamp_flutter_blue_plus_bluetooth_usage(installer, description)
  plist_path = File.join(
    installer.sandbox.root.to_s,
    'Target Support Files',
    'flutter_blue_plus_darwin',
    'flutter_blue_plus_darwin-Info.plist'
  )

  return unless File.exist?(plist_path)

  plist = Xcodeproj::Plist.read_from_path(plist_path) || {}
  plist['NSBluetoothAlwaysUsageDescription'] = description
  plist['NSBluetoothPeripheralUsageDescription'] = description
  Xcodeproj::Plist.write_to_path(plist, plist_path)
end

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  bluetooth_usage_description = 'ChickMark uses Bluetooth to read live temperature and relative humidity from nearby Govee sensors during hatchery audits.'

  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)

    next unless target.name == 'flutter_blue_plus_darwin'

    target.build_configurations.each do |config|
      config.build_settings['INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription'] = bluetooth_usage_description
      config.build_settings['INFOPLIST_KEY_NSBluetoothPeripheralUsageDescription'] = bluetooth_usage_description
    end
  end

  stamp_flutter_blue_plus_bluetooth_usage(installer, bluetooth_usage_description)
end
