-- 0002 full sync schema: remaining tables the client pushes/pulls + photos storage bucket
--
-- Builds on 0001 (customers, hatcheries, flocks, audit_sessions). Same conventions:
-- snake_case, text ids, text/ISO dates, integer booleans, RLS authenticated = full access.
--
-- Panel tables (egg_storage ... hatcher_optimizing) are GENERATED by
-- tool/gen_supabase_schema.dart from lib/data/models/panel_sample_schema.dart using the
-- client's exact _snakeCase, so columns match what SupabaseService pushes 1:1.
--
-- `users` is intentionally deferred (read-only/vestigial; nothing populates it remotely yet).

-- ============================ reference / benchmark (pull-only) ============================
create table public.bmk_breeds (
  id              text primary key,
  breed           text not null,
  age_week        integer not null,
  hatchability_pct double precision default 0,
  fertility_pct    double precision default 0,
  hof_pct          double precision default 0,
  production_pct   double precision default 0,
  egg_weight_g     double precision default 0,
  chick_weight_g   double precision default 0
);
alter table public.bmk_breeds enable row level security;
create policy authenticated_all on public.bmk_breeds for all to authenticated using (true) with check (true);

create table public.bmk_egg_breakout (
  id              text primary key,
  age_week        integer not null unique,
  infertile_pct   double precision default 0,
  early24h_pct    double precision default 0,
  early48h_pct    double precision default 0,
  blood_ring_pct  double precision default 0,
  black_eye_pct   double precision default 0,
  early_dead_pct  double precision default 0,
  mid_dead_pct    double precision default 0,
  late_dead_pct   double precision default 0,
  external_pip_pct double precision default 0,
  cracked_pct     double precision default 0,
  contam_pct      double precision default 0
);
alter table public.bmk_egg_breakout enable row level security;
create policy authenticated_all on public.bmk_egg_breakout for all to authenticated using (true) with check (true);

-- ============================ govee daily captures (push + pull) ===========================
create table public.govee_daily_captures (
  id                text primary key,
  customer_id       text not null references public.customers(id)  on delete cascade,
  hatchery_id       text not null references public.hatcheries(id) on delete cascade,
  station_key       text not null default '',
  place             text not null,
  machine_id        text not null default '',
  capture_date      text not null,
  started_at        text,
  ended_at          text,
  device_id         text,
  device_name       text,
  status            text not null,
  temp_avg          double precision,
  temp_min          double precision,
  temp_max          double precision,
  temp_sd           double precision,
  temp_cv_pct       double precision,
  rh_avg            double precision,
  rh_min            double precision,
  rh_max            double precision,
  rh_sd             double precision,
  rh_cv_pct         double precision,
  reading_count     integer not null,
  chart_points_json text not null default '[]',
  created_at        text not null,
  updated_at        text not null
);
create index idx_govee_daily_dashboard on public.govee_daily_captures(customer_id, hatchery_id, capture_date);
alter table public.govee_daily_captures enable row level security;
create policy authenticated_all on public.govee_daily_captures for all to authenticated using (true) with check (true);

-- ============================ sync tombstones (push + pull) ================================
create table public.sync_tombstones (
  id         text primary key,
  table_name text not null,
  row_id     text not null,
  deleted_at text not null,
  created_at text not null,
  synced_at  text,
  last_error text
);
create index idx_sync_tombstones_target on public.sync_tombstones(table_name, row_id);
alter table public.sync_tombstones enable row level security;
create policy authenticated_all on public.sync_tombstones for all to authenticated using (true) with check (true);

-- ============================ photos (metadata; binaries in storage) =======================
create table public.photos (
  id            text primary key,
  file_path     text,
  description   text,
  created_at    text,
  session_id    text not null references public.audit_sessions(id) on delete cascade,
  panel_name    text not null,
  panel_row_id  text not null,
  field_key     text not null,
  upload_status text not null default 'local'
);
create index idx_photos_panel on public.photos(session_id, panel_name, panel_row_id);
alter table public.photos enable row level security;
create policy authenticated_all on public.photos for all to authenticated using (true) with check (true);

-- ============================ panel sample tables (generated) ==============================
create table public.egg_storage (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  est_readings_json text,
  est_avg double precision,
  est_cv_pct double precision,
  turning_times integer,
  tray_spacing text,
  cooler_proximity text,
  condensation_present integer,
  upside_down_count integer,
  upside_down_pct double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_egg_storage_session on public.egg_storage(session_id);
create index idx_egg_storage_dashboard on public.egg_storage(customer_id, flock_id, date);
alter table public.egg_storage enable row level security;
create policy authenticated_all on public.egg_storage for all to authenticated using (true) with check (true);

create table public.egg_quality (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  uv_tray_egg_count integer,
  uv_cuticle_damage_count integer,
  uv_cuticle_damage_pct double precision,
  uv_washed_count integer,
  uv_washed_pct double precision,
  uv_dirty_count integer,
  uv_dirty_pct double precision,
  uv_affected_count integer,
  uv_affected_pct double precision,
  egg_weights_json text,
  egg_sample_size integer,
  egg_avg_weight double precision,
  egg_uniformity_pct double precision,
  egg_cv_pct double precision,
  egg_bmk_age_weeks integer,
  egg_bmk_weight double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_egg_quality_session on public.egg_quality(session_id);
create index idx_egg_quality_dashboard on public.egg_quality(customer_id, flock_id, date);
alter table public.egg_quality enable row level security;
create policy authenticated_all on public.egg_quality for all to authenticated using (true) with check (true);

create table public.chick_quality (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  pasgar_sample_size integer,
  pasgar_reflexes_count integer,
  pasgar_beak_count integer,
  pasgar_navel_count integer,
  pasgar_belly_count integer,
  pasgar_leg_count integer,
  pasgar_feather_dev_count integer,
  pasgar_reflexes_pct double precision,
  pasgar_beak_pct double precision,
  pasgar_navel_pct double precision,
  pasgar_belly_pct double precision,
  pasgar_leg_pct double precision,
  pasgar_feather_dev_pct double precision,
  pasgar_final_score double precision,
  yfbm_photo text,
  yfbm_entries_json text,
  yfbm_entry_count integer,
  yfbm_avg_pct double precision,
  yfbm_cv_pct double precision,
  cvt_readings_json text,
  cvt_photos_json text,
  cvt_sample_size integer,
  cvt_top_basket text,
  cvt_top_temp double precision,
  cvt_top_photo text,
  cvt_middle_basket text,
  cvt_middle_temp double precision,
  cvt_middle_photo text,
  cvt_bottom_basket text,
  cvt_bottom_temp double precision,
  cvt_bottom_photo text,
  cvt_avg_temp double precision,
  cvt_cv_pct double precision,
  pm_sample_size integer,
  pm_collection_point text,
  pm_omphalitis_count integer,
  pm_omphalitis_severity text,
  pm_gaseous_ceca_count integer,
  pm_gaseous_ceca_severity text,
  pm_gizzard_erosions_count integer,
  pm_gizzard_erosions_severity text,
  pm_air_sac_caseations_count integer,
  pm_air_sac_caseations_severity text,
  pm_urolithiasis_count integer,
  pm_urolithiasis_severity text,
  pm_nephritis_count integer,
  pm_nephritis_severity text,
  pm_general_septicemia_count integer,
  pm_general_septicemia_severity text,
  pm_other_lesions_json text,
  pm_suspected_cause_auto text,
  pm_suspected_cause_manual text,
  pm_photos_json text,
  culled_chicks_total_egg_set integer,
  culled_chicks_analysis_json text,
  culled_chicks_affected_pct double precision,
  culled_chicks_top_category text,
  culled_chicks_top_subtype text,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_chick_quality_session on public.chick_quality(session_id);
create index idx_chick_quality_dashboard on public.chick_quality(customer_id, flock_id, date);
alter table public.chick_quality enable row level security;
create policy authenticated_all on public.chick_quality for all to authenticated using (true) with check (true);

create table public.chick_weights (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  weights_json text,
  sample_size integer,
  avg_weight double precision,
  uniformity_pct double precision,
  cv_pct double precision,
  bmk_weight double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_chick_weights_session on public.chick_weights(session_id);
create index idx_chick_weights_dashboard on public.chick_weights(customer_id, flock_id, date);
alter table public.chick_weights enable row level security;
create policy authenticated_all on public.chick_weights for all to authenticated using (true) with check (true);

create table public.fresh_egg_breakout (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  tray_size integer,
  infertile_count integer,
  early24h_count integer,
  early48h_count integer,
  blood_ring_count integer,
  infertile_pct double precision,
  early24h_pct double precision,
  early48h_pct double precision,
  blood_ring_pct double precision,
  infertile_diff_pct double precision,
  early24h_diff_pct double precision,
  early48h_diff_pct double precision,
  blood_ring_diff_pct double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_fresh_egg_breakout_session on public.fresh_egg_breakout(session_id);
create index idx_fresh_egg_breakout_dashboard on public.fresh_egg_breakout(customer_id, flock_id, date);
alter table public.fresh_egg_breakout enable row level security;
create policy authenticated_all on public.fresh_egg_breakout for all to authenticated using (true) with check (true);

create table public.candled_egg_breakout (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  candling_day integer,
  tray_size integer,
  infertile_count integer,
  early24h_count integer,
  early48h_count integer,
  blood_ring_count integer,
  black_eye_count integer,
  infertile_pct double precision,
  early24h_pct double precision,
  early48h_pct double precision,
  blood_ring_pct double precision,
  black_eye_pct double precision,
  infertile_diff_pct double precision,
  early24h_diff_pct double precision,
  early48h_diff_pct double precision,
  blood_ring_diff_pct double precision,
  black_eye_diff_pct double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_candled_egg_breakout_session on public.candled_egg_breakout(session_id);
create index idx_candled_egg_breakout_dashboard on public.candled_egg_breakout(customer_id, flock_id, date);
alter table public.candled_egg_breakout enable row level security;
create policy authenticated_all on public.candled_egg_breakout for all to authenticated using (true) with check (true);

create table public.residue_breakout (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  house text,
  setter text,
  hatcher text,
  trolley text,
  tray text,
  position text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  tray_size integer,
  infertile_count integer,
  early_dead_count integer,
  mid_dead_count integer,
  late_dead_count integer,
  external_pip_count integer,
  cracked_count integer,
  contaminated_count integer,
  infertile_pct double precision,
  early_dead_pct double precision,
  mid_dead_pct double precision,
  late_dead_pct double precision,
  external_pip_pct double precision,
  cracked_pct double precision,
  contaminated_pct double precision,
  infertile_diff_pct double precision,
  early_dead_diff_pct double precision,
  mid_dead_diff_pct double precision,
  late_dead_diff_pct double precision,
  external_pip_diff_pct double precision,
  cracked_diff_pct double precision,
  contaminated_diff_pct double precision,
  total_eggs_set integer,
  hatched_count integer,
  culled_count integer,
  dead_count integer,
  hatchability_pct double precision,
  fertility_pct double precision,
  hof_pct double precision,
  culled_pct double precision,
  dead_pct double precision,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_residue_breakout_session on public.residue_breakout(session_id);
create index idx_residue_breakout_dashboard on public.residue_breakout(customer_id, flock_id, date);
alter table public.residue_breakout enable row level security;
create policy authenticated_all on public.residue_breakout for all to authenticated using (true) with check (true);

create table public.setter_optimizing (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  setter text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  machine_type text,
  setpoint_f double precision,
  actual_f double precision,
  setpoint_rh double precision,
  actual_rh double precision,
  batch_size integer,
  batch_count integer,
  total_eggs_set integer,
  turning_angle double precision,
  co2_ppm double precision,
  co2_photo text,
  est_breed text,
  incubation_age_days integer,
  incubation_hours integer,
  est_readings_json text,
  est_photos_json text,
  est_samples_json text,
  est_sample_size integer,
  est_avg double precision,
  est_cv_pct double precision,
  machine_screen_photo text,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_setter_optimizing_session on public.setter_optimizing(session_id);
create index idx_setter_optimizing_dashboard on public.setter_optimizing(customer_id, flock_id, date);
alter table public.setter_optimizing enable row level security;
create policy authenticated_all on public.setter_optimizing for all to authenticated using (true) with check (true);

create table public.hatcher_optimizing (
  id text primary key,
  session_id text not null,
  customer_id text not null,
  flock_id text,
  hatchery_id text,
  date text not null,
  breed text,
  flock_age_weeks integer,
  hatcher text,
  storage_period_days integer,
  bmk_age_weeks integer,
  notes text,
  created_at text not null,
  updated_at text not null,
  sync_status text not null default 'pending',
  last_synced_at text,
  sync_error text,
  setpoint_f double precision,
  setpoint_rh double precision,
  incubation_age_days integer,
  incubation_hours integer,
  co2_ppm double precision,
  co2_photo text,
  cvt_readings_json text,
  cvt_photos_json text,
  cvt_sample_size integer,
  cvt_avg double precision,
  cvt_cv_pct double precision,
  chick_panting integer,
  chick_panting_photo text,
  meconium text,
  transfer_day integer,
  foreign key (session_id) references public.audit_sessions(id) on delete cascade,
  foreign key (customer_id) references public.customers(id) on delete cascade,
  foreign key (flock_id) references public.flocks(id) on delete cascade,
  foreign key (hatchery_id) references public.hatcheries(id) on delete cascade
);
create index idx_hatcher_optimizing_session on public.hatcher_optimizing(session_id);
create index idx_hatcher_optimizing_dashboard on public.hatcher_optimizing(customer_id, flock_id, date);
alter table public.hatcher_optimizing enable row level security;
create policy authenticated_all on public.hatcher_optimizing for all to authenticated using (true) with check (true);

-- ============================ photos storage bucket ========================================
insert into storage.buckets (id, name, public)
values ('photos', 'photos', false)
on conflict (id) do nothing;

drop policy if exists photos_authenticated_all on storage.objects;
create policy photos_authenticated_all on storage.objects
  for all to authenticated
  using (bucket_id = 'photos')
  with check (bucket_id = 'photos');
